@startuml Marketing-Project Class Diagram
class User {
    name: string
    testedInterests: [Interest]
    starredInterests: [Interest]
    constructor(name: string, testedInterests: [Interest], starredInterests: [Interest])
    createInterest(name: Interest)
    testInterest(interest: Interest)
    starInterest(interest: Interest)
}

class Interest {
    name: string
    tested: boolean
    starred: boolean
    totalSpent: number
    constructor(name: string, tested: boolean, starred: boolean)
}

class Project {
    name: string
    startDate: Date
    active: boolean
    client: string
    product: string
    interests: [Interest]
    constructor(name: string, startDate: date, active: boolean, interests: [Interest])
}

class Login {
    
}

User "1" *----> "0..*" Interest : tests, stars
User "1" *----> "0..*" Project : creates, has
Project o----> "0..*" Interest : contains

@enduml