@startuml Marketing-Project Class Diagram
class User {
    name: string
    email: string
    testedInterests: [Interest]
    starredInterests: [Interest]
    projects: [Project]
    constructor(name: string, email: string)
    createInterest(name: string)
    testInterest(interest: Interest)
    starInterest(interest: Interest)
}

class Interest {
    name: string
    tested: boolean
    starred: boolean
    totalSpent: number
    testedAt: Date
    constructor(name: string)
}

class Project {
    name: string
    startDate: Date
    endDate: Date
    client: string
    interests: [Interest]
    constructor(name: string, startDate: Date, endDate: Date)
    addInterest(interest: Interest)
    removeInterest(interest: Interest)
}

class Login {}

class SignUp {}

class spendManager {}

User "1" *----> "0..*" Interest : tests, stars
User "1" *----> "0..*" Project : creates, has
Project o----> "0..*" Interest : contains

@enduml